### ISSUE TITLE
Hashing trick with libsvm format?

### ISSUE THREAD

**Issue by sergeyf** [ryanbressler/CloudForest#52]
Howdy,

Your package looks really great. I have a lot of NLPish data and so it would be great to be able to use sparse data with strings instead of integers. Sort of like VW, but with fewer bells and whistles.

Is this very difficult to add?

Thanks for the awesome open source software!

**Comment by ryanbressler** [comment]
It should be pretty easy to do this...DenseCatFeature uses a simple hashing scheme internally and the (dense) feature matrix and arff parser will use it.  You could just change the part of the lib svm parser that parses every feature as a DenseNumFeature to use Cat Features:

https://github.com/ryanbressler/CloudForest/blob/master/libsvm.go#L76

I may be missing something else but i think the interfaces are pretty similar.

It will still use a dense integer data representation internally (and store the int equivalent of each label in a hash). And the code for finding splits in highly dimensional categorical data (the various BestSplit functions in DenseCatFeature) could be faster if it used some sort of heuristic.

**Comment by sergeyf** [comment]
Great, thanks! Adding this feature might be a good way to learn Go, if I find the time on my hands.

**Comment by ryanbressler** [comment]
If you find yourself looking for go projects support sparse arff files could be usefull too (as it would support a mix of categorical and numerical data in a way that might be painfull in libsvm).
